# /// script
# requires-python = ">=3.12"
# dependencies = ["fonttools[woff]==4.65.0"]
# ///
"""Bundle complete fonts as WOFF2, preserving Vietnamese combining marks.

Run: uv run scripts/vendor_fonts.py
Normal MkDocs builds use the checked-in assets and need no font tooling/network.
"""

from concurrent.futures import ThreadPoolExecutor
import hashlib
from io import BytesIO
import json
from pathlib import Path
from urllib.parse import quote
from urllib.request import Request, urlopen

from fontTools import subset
from fontTools.ttLib import TTFont


ROOT = Path(__file__).resolve().parents[1]
DEST = ROOT / "docs/assets/fonts"
FAMILIES = {
    "manrope": ("Manrope", ["Manrope[wght].ttf"]),
    "inter": ("Inter", ["Inter[opsz,wght].ttf", "Inter-Italic[opsz,wght].ttf"]),
    "lora": ("Lora", ["Lora[wght].ttf", "Lora-Italic[wght].ttf"]),
    "ibmplexmono": ("IBM Plex Mono", [
        "IBMPlexMono-Regular.ttf", "IBMPlexMono-Medium.ttf",
        "IBMPlexMono-SemiBold.ttf", "IBMPlexMono-Bold.ttf",
        "IBMPlexMono-Italic.ttf", "IBMPlexMono-BoldItalic.ttf",
    ]),
    "delagothicone": ("Dela Gothic One", ["DelaGothicOne-Regular.ttf"]),
}


def fetch(url):
    request = Request(url, headers={"User-Agent": "BehindThePipeline-font-vendor"})
    with urlopen(request, timeout=90) as response:
        return response.read()


def vendor_family(item, revision):
    slug, (family, filenames) = item
    base = f"https://raw.githubusercontent.com/google/fonts/{revision}/ofl/{slug}/"
    rules, sources = [], []
    for source_name in filenames:
        url = base + quote(source_name)
        source = fetch(url)
        font = TTFont(BytesIO(source))
        # Dela includes a large Japanese character set that this site does not
        # use. Keep Latin, Vietnamese, combining marks, and common symbols in
        # one face so decomposed text cannot cross unicode-range boundaries.
        if slug == "delagothicone":
            options = subset.Options()
            options.layout_features = ["*"]
            options.name_IDs = ["*"]
            options.name_legacy = True
            options.name_languages = ["*"]
            subsetter = subset.Subsetter(options=options)
            subsetter.populate(unicodes=[
                *range(0x0000, 0x0370), *range(0x1E00, 0x1F00),
                *range(0x2000, 0x2800),
            ])
            subsetter.subset(font)
        style = "italic" if font["head"].macStyle & 2 else "normal"
        weight = str(font["OS/2"].usWeightClass)
        if "fvar" in font:
            axis = next(axis for axis in font["fvar"].axes if axis.axisTag == "wght")
            weight = f"{axis.minValue:g} {axis.maxValue:g}"
        filename = f"{slug}-{style}-{weight.replace(' ', '-')}.woff2"
        font.flavor = "woff2"
        font.save(DEST / filename)
        sources.append({
            "file": filename,
            "url": url,
            "source_sha256": hashlib.sha256(source).hexdigest(),
            "sha256": hashlib.sha256((DEST / filename).read_bytes()).hexdigest(),
            "subset": "U+0000-036F,U+1E00-1EFF,U+2000-27FF" if slug == "delagothicone" else None,
        })
        rules.append(f'''@font-face {{
  font-family: "{family}";
  font-style: {style};
  font-weight: {weight};
  font-display: swap;
  src: url("../assets/fonts/{filename}") format("woff2");
}}''')
    license_url = base + "OFL.txt"
    (DEST / f"{slug}-OFL.txt").write_bytes(fetch(license_url))
    return "\n\n".join(rules), {"family": slug, "license_url": license_url, "files": sources}


def main():
    DEST.mkdir(parents=True, exist_ok=True)
    manifest = DEST / "sources.json"
    previous = json.loads(manifest.read_text()) if manifest.exists() else []
    revision = json.loads(fetch("https://api.github.com/repos/google/fonts/commits/main"))["sha"]
    with ThreadPoolExecutor(max_workers=5) as pool:
        results = list(pool.map(lambda item: vendor_family(item, revision), FAMILIES.items()))
    css = "/* Generated by scripts/vendor_fonts.py. Complete fonts include Vietnamese combining marks. */\n\n"
    css += "\n\n".join(rules for rules, _ in results)
    css += '''

:root {
  --md-text-font: "Manrope";
  --md-code-font: "IBM Plex Mono";
  --landing-display-font: "Lora", Georgia, serif;
}
'''
    (ROOT / "docs/stylesheets/fonts.css").write_text(css)
    sources = [source for _, source in results]
    manifest.write_text(json.dumps(sources, indent=2) + "\n")
    current_files = {file["file"] for source in sources for file in source["files"]}
    # Remove only obsolete generated fonts recorded by the previous manifest.
    for source in previous:
        for file in source["files"]:
            path = DEST / file["file"]
            if path.name not in current_files and path.suffix == ".woff2" and path.parent == DEST:
                path.unlink(missing_ok=True)
    print(f"Vendored {len(current_files)} WOFF2 files from google/fonts {revision}")


if __name__ == "__main__":
    main()
